export const localityList = [
    { value: "A Coruña", label: "A Coruña" },
    { value: "Abegondo", label: "Abegondo" },
    { value: "Ames", label: "Ames" },
    { value: "Aranga", label: "Aranga" },
    { value: "Ares", label: "Ares" },
    { value: "Arteixo", label: "Arteixo" },
    { value: "Arzúa", label: "Arzúa" },
    { value: "As Pontes de García Rodríguez", label: "As Pontes de García Rodríguez" },
    { value: "Baña, A", label: "Baña, A" },
    { value: "Bergondo", label: "Bergondo" },
    { value: "Betanzos", label: "Betanzos" },
    { value: "Boimorto", label: "Boimorto" },
    { value: "Boiro", label: "Boiro" },
    { value: "Boqueixón", label: "Boqueixón" },
    { value: "Brión", label: "Brión" },
    { value: "Cabana de Bergantiños", label: "Cabana de Bergantiños" },
    { value: "Cabanas", label: "Cabanas" },
    { value: "Camariñas", label: "Camariñas" },
    { value: "Cambre", label: "Cambre" },
    { value: "Capela, A", label: "Capela, A" },
    { value: "Carballo", label: "Carballo" },
    { value: "Cariño", label: "Cariño" },
    { value: "Carnota", label: "Carnota" },
    { value: "Carral", label: "Carral" },
    { value: "Cedeira", label: "Cedeira" },
    { value: "Cee", label: "Cee" },
    { value: "Cerceda", label: "Cerceda" },
    { value: "Cerdido", label: "Cerdido" },
    { value: "Coirós", label: "Coirós" },
    { value: "Corcubión", label: "Corcubión" },
    { value: "Coristanco", label: "Coristanco" },
    { value: "Culleredo", label: "Culleredo" },
    { value: "Curtis", label: "Curtis" },
    { value: "Dodro", label: "Dodro" },
    { value: "Dumbría", label: "Dumbría" },
    { value: "Fene", label: "Fene" },
    { value: "Ferrol", label: "Ferrol" },
    { value: "Fisterra", label: "Fisterra" },
    { value: "Frades", label: "Frades" },
    { value: "Irixoa", label: "Irixoa" },
    { value: "A Laracha", label: "A Laracha"},
    { value: "Laxe", label: "Laxe" },
    { value: "Lousame", label: "Lousame" },
    { value: "Malpica de Bergantiños", label: "Malpica de Bergantiños" },
    { value: "Mañón", label: "Mañón" },
    { value: "Mazaricos", label: "Mazaricos" },
    { value: "Melide", label: "Melide" },
    { value: "Mesía", label: "Mesía" },
    { value: "Miño", label: "Miño" },
    { value: "Moeche", label: "Moeche" },
    { value: "Monfero", label: "Monfero" },
    { value: "Mugardos", label: "Mugardos" },
    { value: "Muros", label: "Muros" },
    { value: "Muxía", label: "Muxía" },
    { value: "Narón", label: "Narón" },
    { value: "Neda", label: "Neda" },
    { value: "Negreira", label: "Negreira" },
    { value: "Noia", label: "Noia" },
    { value: "Oleiros", label: "Oleiros" },
    { value: "Ordes", label: "Ordes" },
    { value: "Oroso", label: "Oroso" },
    { value: "Ortigueira", label: "Ortigueira" },
    { value: "Outes", label: "Outes" },
    { value: "Oza-Cesuras", label: "Oza-Cesuras" },
    { value: "Paderne", label: "Paderne" },
    { value: "Padrón", label: "Padrón" },
    { value: "Pino (O)", label: "Pino (O)" },
    { value: "Pobra do Caramiñal (A)", label: "Pobra do Caramiñal (A)" },
    { value: "Ponteceso", label: "Ponteceso" },
    { value: "Pontedeume", label: "Pontedeume" },
    { value: "Pontes de García Rodríguez (As)", label: "Pontes de García Rodríguez (As)" },
    { value: "Porto do Son", label: "Porto do Son" },
    { value: "Rianxo", label: "Rianxo" },
    { value: "Ribeira", label: "Ribeira" },
    { value: "Rois", label: "Rois" },
    { value: "Sada", label: "Sada" },
    { value: "San Sadurniño", label: "San Sadurniño" },
    { value: "Santa Comba", label: "Santa Comba" },
    { value: "Santiago de Compostela", label: "Santiago de Compostela" },
    { value: "Santiso", label: "Santiso" },
    { value: "Sobrado", label: "Sobrado" },
    { value: "Somozas (As)", label: "Somozas (As)" },
    { value: "Teo", label: "Teo" },
    { value: "Toques", label: "Toques" },
    { value: "Tordoia", label: "Tordoia" },
    { value: "Touro", label: "Touro" },
    { value: "Valdoviño", label: "Valdoviño" },
    { value: "Vilarmaior", label: "Vilarmaior" },
    { value: "Vilasantar", label: "Vilasantar" },
    { value: "Vimianzo", label: "Vimianzo" },
    { value: "Zas", label: "Zas" },
];